[build]
rustflags = [

             "-A", "non_camel_case_types",
             "-A", "non_snake_case",
             "-A", "dead_code",
             "-A", "non_upper_case_globals"
             
            ]